In [233]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.utils import to_categorical
import pandas as pd
import tensorflow as tf
import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
import re
import string
import tensorflow_hub as hub
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [234]:
df = pd.read_csv("/kaggle/input/resume-dataset/Resume/Resume.csv")

In [235]:
categories_l = len(df['Category'].unique())
cats = list(df['Category'].unique())

In [236]:
cats

['HR',
 'DESIGNER',
 'INFORMATION-TECHNOLOGY',
 'TEACHER',
 'ADVOCATE',
 'BUSINESS-DEVELOPMENT',
 'HEALTHCARE',
 'FITNESS',
 'AGRICULTURE',
 'BPO',
 'SALES',
 'CONSULTANT',
 'DIGITAL-MEDIA',
 'AUTOMOBILE',
 'CHEF',
 'FINANCE',
 'APPAREL',
 'ENGINEERING',
 'ACCOUNTANT',
 'CONSTRUCTION',
 'PUBLIC-RELATIONS',
 'BANKING',
 'ARTS',
 'AVIATION']

In [237]:
df

ID                                         Resume_str  \
0     16852973           HR ADMINISTRATOR/MARKETING ASSOCIATE\...   
1     22323967           HR SPECIALIST, US HR OPERATIONS      ...   
2     33176873           HR DIRECTOR       Summary      Over 2...   
3     27018550           HR SPECIALIST       Summary    Dedica...   
4     17812897           HR MANAGER         Skill Highlights  ...   
...        ...                                                ...   
2479  99416532           RANK: SGT/E-5 NON- COMMISSIONED OFFIC...   
2480  24589765           GOVERNMENT RELATIONS, COMMUNICATIONS ...   
2481  31605080           GEEK SQUAD AGENT         Professional...   
2482  21190805           PROGRAM DIRECTOR / OFFICE MANAGER    ...   
2483  37473139           STOREKEEPER II       Professional Sum...   

                                            Resume_html  Category  
0     <div class="fontsize fontface vmargins hmargin...        HR  
1     <div class="fontsize fontface vmargins hmargin...        HR  
2     <div class="fontsize fontface vmargins hmargin...        HR  
3     <div class="fontsize fontface vmargins hmargin...        HR  
4     <div class="fontsize fontface vmargins hmargin...        HR  
...                                                 ...       ...  
2479  <div class="fontsize fontface vmargins hmargin...  AVIATION  
2480  <div class="fontsize fontface vmargins hmargin...  AVIATION  
2481  <div class="fontsize fontface vmargins hmargin...  AVIATION  
2482  <div class="fontsize fontface vmargins hmargin...  AVIATION  
2483  <div class="fontsize fontface vmargins hmargin...  AVIATION  

[2484 rows x 4 columns]

In [238]:
df = df.sample(frac=1)

In [239]:
df

ID                                         Resume_str  \
2156  26579709           MORTGAGE BANKING RESEARCH SPECIALIST ...   
1501  18975686           FINANCE MANAGER       Summary    Outg...   
943   19532392           LOGISTICS TECHNICIAN           Profes...   
1034  23296286           SALES ASSOCIATE         Core Strength...   
886   27903191           DIGITAL MARKETING LEAD       Summary ...   
...        ...                                                ...   
625   47067533           DIRECTOR, BUSINESS DEVELOPMENT       ...   
938   16653657           QUALITY ASSURANCE ASSOCIATE       Sum...   
1207  15083600           PRINCIPAL CONSULTANT       Profession...   
2267  15306049           ARTS EDUCATION INTERN       Objective...   
1903  13701259           SENIOR ACCOUNTANT       Summary    Se...   

                                            Resume_html              Category  
2156  <div class="fontsize fontface vmargins hmargin...               BANKING  
1501  <div class="fontsize fontface vmargins hmargin...               FINANCE  
943   <div class="fontsize fontface vmargins hmargin...           AGRICULTURE  
1034  <div class="fontsize fontface vmargins hmargin...                 SALES  
886   <div class="fontsize fontface vmargins hmargin...               FITNESS  
...                                                 ...                   ...  
625   <div class="fontsize fontface vmargins hmargin...  BUSINESS-DEVELOPMENT  
938   <div class="fontsize fontface vmargins hmargin...           AGRICULTURE  
1207  <div class="fontsize fontface vmargins hmargin...            CONSULTANT  
2267  <div class="fontsize fontface vmargins hmargin...                  ARTS  
1903  <div class="fontsize fontface vmargins hmargin...            ACCOUNTANT  

[2484 rows x 4 columns]

In [240]:
cats[0]

'HR'

In [248]:
cats

['HR',
 'DESIGNER',
 'INFORMATION-TECHNOLOGY',
 'TEACHER',
 'ADVOCATE',
 'BUSINESS-DEVELOPMENT',
 'HEALTHCARE',
 'FITNESS',
 'AGRICULTURE',
 'BPO',
 'SALES',
 'CONSULTANT',
 'DIGITAL-MEDIA',
 'AUTOMOBILE',
 'CHEF',
 'FINANCE',
 'APPAREL',
 'ENGINEERING',
 'ACCOUNTANT',
 'CONSTRUCTION',
 'PUBLIC-RELATIONS',
 'BANKING',
 'ARTS',
 'AVIATION']

In [256]:
y = []
for index, row in df.iterrows():
    r = []
    for j in range(categories_l):
        if(row['Category'] == cats[j]):
            r.append(1)
        else:
            r.append(0)
    y.append(r)
    


In [257]:
y = np.array(y).astype(np.float64)

In [258]:
y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0.])

In [259]:
X = (df["Resume_str"].str.lower().replace('\s+', ' ').replace('\n', ' ')).values

In [260]:
# Example to ensure all entries are strings (Python way, not the most efficient for large data)
X = [str(entry) for entry in X]

In [261]:
X = np.array(X)

In [262]:
vocab_size = 1500
embedding_dim = 32
max_length = 1000
trunc_type='post'
padding_type='post'
oov_tok = "<OOV>"


In [263]:
tokenizer = Tokenizer(num_words = vocab_size, oov_token=oov_tok)
tokenizer.fit_on_texts(X)
word_index = tokenizer.word_index

In [264]:
y[55]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [267]:
cats[np.argmax(y[55])]

'INFORMATION-TECHNOLOGY'

In [268]:
type(X)

numpy.ndarray

In [269]:
X_seq = tokenizer.texts_to_sequences(X)
X_pad = np.array(pad_sequences(X_seq, maxlen=max_length, padding=padding_type, truncating=trunc_type))

In [288]:

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(32, activation='sigmoid'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(64, activation='sigmoid'),
    #tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(categories_l, activation='softmax')
])
model.compile(optimizer='adam',
              loss=tf.keras.losses.CategoricalCrossentropy(from_logits=False),
              metrics=['accuracy'])
#model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()
#model.compile(loss='sparse_categorical_crossentropy',optimizer='Adam')
#ops = tf.keras.optimizers.Adagrad(
  #  learning_rate=1)


/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:86: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_13 (Embedding)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d_13     │ ?                      │   0 (unbuilt) │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_36 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_37 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_38 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [289]:
model.fit(X_pad, y, epochs=500, batch_size=32, validation_split=0.25)

Epoch 1/500
59/59 ━━━━━━━━━━━━━━━━━━━━ 8s 66ms/step - accuracy: 0.0364 - loss: 3.3069 - val_accuracy: 0.0403 - val_loss: 3.1496
Epoch 2/500
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0480 - loss: 3.2278 - val_accuracy: 0.0386 - val_loss: 3.1456
Epoch 3/500
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0428 - loss: 3.2025 - val_accuracy: 0.0403 - val_loss: 3.1418
Epoch 4/500
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0462 - loss: 3.2065 - val_accuracy: 0.0531 - val_loss: 3.1417
Epoch 5/500
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0439 - loss: 3.1925 - val_accuracy: 0.0483 - val_loss: 3.1401
Epoch 6/500
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0394 - loss: 3.2106 - val_accuracy: 0.0403 - val_loss: 3.1424
Epoch 7/500
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0591 - loss: 3.1652 - val_accuracy: 0.0419 - val_loss: 3.1375
Epoch 8/500
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0440 - loss: 3.1698 - val_accuracy: 0.0515 - 

In [290]:
sentence = ["""Education
University of Guelph Sep. 2023 – Apr. 2028
Bachelor of Engineering in Computer Engineering CO-OP, Minor in Entrepreneurship Guelph, ON
GPA(Sem 1): 91.9%
Experience
University of Guelph Robotics Team Software Member Sep. 2023 – Present
University of Guelph Guelph, ON
• Experience with using WSL and Linux to navigate robotics workspaces and programs
• Python programming to control robot simulations, image processing for simulation camera output
• Image augmentation with opencv and soon tensorflow and onnx for shrub detection(ongoing)
• Introduced to using docker for multi-platform deployment of robotics code
Guelph AI Club Technical Lead and Executive Jan. 2024 – Present
University of Guelph Guelph, ON
• Present and prepare workshops/demonstrations of key AI libraries with python
• Pandas basics workshop, continuing work with Numpy, MatplotLib, Tensorflow, SkLearn
• Usage of Google Colab for data handling and live demonstration
• Creating interactive sample code for beginners to learn effectively
Guelph CyberSecurity Club Jarvis AI Project Lead Jan. 2024 – present
University of Guelph Guelph, ON
• Lead a team to create an AI assistant similar to Jarvis from Iron Man
"""]

sequences = tokenizer.texts_to_sequences(sentence)
padded = pad_sequences(sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)
p = model.predict(padded)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step


In [291]:
cats[np.argmax(p)]

'SALES'

In [292]:
np.argmax(p)

10

In [293]:
p

array([[3.0773321e-11, 1.7221643e-02, 6.7180226e-06, 1.1014503e-04,
        1.0309936e-05, 4.2859647e-02, 6.8441632e-06, 5.8656831e-05,
        2.1527385e-02, 2.2797167e-02, 3.0156744e-01, 1.4837865e-03,
        7.2437944e-04, 6.1770510e-02, 1.0906302e-02, 1.7737912e-08,
        2.8048521e-01, 4.3992180e-02, 4.1495080e-12, 1.6085267e-01,
        1.4870848e-07, 1.2305462e-05, 2.8292242e-02, 5.3144521e-03]],
      dtype=float32)

In [294]:
np.max(p)

0.30156744

In [295]:
model.save('model.h5')

In [296]:
indices = np.argsort(p)[0][::-1]

In [297]:
indices

array([10, 16, 19, 13, 17,  5, 22,  9,  8,  1, 14, 23, 11, 12,  3,  7, 21,
        4,  6,  2, 20, 15,  0, 18])

In [298]:
indices[0]

10

In [299]:
indices

array([10, 16, 19, 13, 17,  5, 22,  9,  8,  1, 14, 23, 11, 12,  3,  7, 21,
        4,  6,  2, 20, 15,  0, 18])

In [300]:
for i in range(0, 3):
    print(cats[indices[i]])
    print(p[0][indices[i]])

SALES
0.30156744
APPAREL
0.2804852
CONSTRUCTION
0.16085267


In [301]:
cats

['HR',
 'DESIGNER',
 'INFORMATION-TECHNOLOGY',
 'TEACHER',
 'ADVOCATE',
 'BUSINESS-DEVELOPMENT',
 'HEALTHCARE',
 'FITNESS',
 'AGRICULTURE',
 'BPO',
 'SALES',
 'CONSULTANT',
 'DIGITAL-MEDIA',
 'AUTOMOBILE',
 'CHEF',
 'FINANCE',
 'APPAREL',
 'ENGINEERING',
 'ACCOUNTANT',
 'CONSTRUCTION',
 'PUBLIC-RELATIONS',
 'BANKING',
 'ARTS',
 'AVIATION']